/*

 BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\kveld\Documents\code\game\gb\snake\assets\sprites.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundWidth 20
#define backgroundHeight 18
#define backgroundBank 0

#define background backgroundPLN0
extern unsigned char backgroundPLN0[];
extern unsigned char backgroundPLN1[];

/* End of BACKGROUND.H */
